### ISSUE TITLE
payload for reset key not added

### ISSUE THREAD

**Issue by saurabh-172** [pranesh239/use-key-capture#4]
@pranesh239 
I think in your code the payload function for the reset key is not been added. if this issue is valid then please assign me to this one I would like to contribute to this by adding the reset key payload action. also which one is the reset key as all the keys including the escape key has been used. And please add hacktoberfest tag if the issue is valid. if this is not valid then sorry for the misunderstanding and in that case I would like to learn what mistakes I have done?

**Comment by saurabh-172** [comment]
What happened did I do some mistake because of which you are not replying? I have closed the PR and have mentioned above what I understood from your explanations, and I have made the changes needed according to the above explanation, so should I make a PR, or what **please reply**?

**Comment by pranesh239** [comment]
hey @saurabh-172 , actually we have `resetKeyData` function already, which does it! 
Sorry for the delay. I was out of station.
